--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-05-04 22:15:17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 885 (class 1247 OID 25428)
-- Name: gender; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.gender AS ENUM (
    'FEMALE',
    'MALE',
    'OTHER'
);


ALTER TYPE public.gender OWNER TO postgres;

--
-- TOC entry 888 (class 1247 OID 25438)
-- Name: userstatus; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.userstatus AS ENUM (
    'ACTIVE',
    'INACTIVE',
    'NONE'
);


ALTER TYPE public.userstatus OWNER TO postgres;

--
-- TOC entry 891 (class 1247 OID 25448)
-- Name: usertype; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.usertype AS ENUM (
    'ADMIN',
    'MANAGER',
    'SYSTEM_ADMIN',
    'USER'
);


ALTER TYPE public.usertype OWNER TO postgres;

--
-- TOC entry 4742 (class 2605 OID 25436)
-- Name: CAST (public.gender AS character varying); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (public.gender AS character varying) WITH INOUT AS IMPLICIT;


--
-- TOC entry 4743 (class 2605 OID 25446)
-- Name: CAST (public.userstatus AS character varying); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (public.userstatus AS character varying) WITH INOUT AS IMPLICIT;


--
-- TOC entry 4744 (class 2605 OID 25458)
-- Name: CAST (public.usertype AS character varying); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (public.usertype AS character varying) WITH INOUT AS IMPLICIT;


--
-- TOC entry 4660 (class 2605 OID 25435)
-- Name: CAST (character varying AS public.gender); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (character varying AS public.gender) WITH INOUT AS IMPLICIT;


--
-- TOC entry 4661 (class 2605 OID 25445)
-- Name: CAST (character varying AS public.userstatus); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (character varying AS public.userstatus) WITH INOUT AS IMPLICIT;


--
-- TOC entry 4662 (class 2605 OID 25457)
-- Name: CAST (character varying AS public.usertype); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (character varying AS public.usertype) WITH INOUT AS IMPLICIT;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 25298)
-- Name: tbl_address; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_address (
                                    address_type integer,
                                    created_at timestamp(6) without time zone,
                                    id bigint NOT NULL,
                                    updated_at timestamp(6) without time zone,
                                    user_id bigint,
                                    apartment_number character varying(255),
                                    building character varying(255),
                                    city character varying(255),
                                    country character varying(255),
                                    floor character varying(255),
                                    street character varying(255),
                                    street_number character varying(255),
                                    created_by character varying(255),
                                    updated_by character varying(255)
);


ALTER TABLE public.tbl_address OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 25297)
-- Name: tbl_address_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 25306)
-- Name: tbl_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_group (
                                  id integer NOT NULL,
                                  role_id integer,
                                  created_at timestamp(6) without time zone,
                                  updated_at timestamp(6) without time zone,
                                  description character varying(255),
                                  name character varying(255),
                                  created_by character varying(255),
                                  updated_by character varying(255)
);


ALTER TABLE public.tbl_group OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 25316)
-- Name: tbl_group_has_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_group_has_user (
                                           group_id integer,
                                           id integer NOT NULL,
                                           created_at timestamp(6) without time zone,
                                           updated_at timestamp(6) without time zone,
                                           user_id bigint,
                                           created_by character varying(255),
                                           updated_by character varying(255)
);


ALTER TABLE public.tbl_group_has_user OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 25315)
-- Name: tbl_group_has_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_group_has_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_group_has_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 25305)
-- Name: tbl_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 25322)
-- Name: tbl_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_permission (
                                       id integer NOT NULL,
                                       created_at timestamp(6) without time zone,
                                       updated_at timestamp(6) without time zone,
                                       description character varying(255),
                                       name character varying(255),
                                       created_by character varying(255),
                                       updated_by character varying(255)
);


ALTER TABLE public.tbl_permission OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 25321)
-- Name: tbl_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 25330)
-- Name: tbl_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_role (
                                 id integer NOT NULL,
                                 created_at timestamp(6) without time zone,
                                 updated_at timestamp(6) without time zone,
                                 description character varying(255),
                                 name character varying(255),
                                 created_by character varying(255),
                                 updated_by character varying(255)
);


ALTER TABLE public.tbl_role OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 25338)
-- Name: tbl_role_has_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_role_has_permission (
                                                id integer NOT NULL,
                                                permission_id integer,
                                                role_id integer,
                                                created_at timestamp(6) without time zone,
                                                updated_at timestamp(6) without time zone,
                                                created_by character varying(255),
                                                updated_by character varying(255)
);


ALTER TABLE public.tbl_role_has_permission OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 25337)
-- Name: tbl_role_has_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_role_has_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_role_has_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 25329)
-- Name: tbl_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 25344)
-- Name: tbl_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_user (
                                 date_of_birth date,
                                 created_at timestamp(6) without time zone,
                                 id bigint NOT NULL,
                                 updated_at timestamp(6) without time zone,
                                 phone character varying(15),
                                 email character varying(255),
                                 first_name character varying(255),
                                 last_name character varying(255),
                                 password character varying(255),
                                 username character varying(255) NOT NULL,
                                 created_by character varying(255),
                                 updated_by character varying(255),
                                 gender public.gender,
                                 status public.userstatus,
                                 type public.usertype
);


ALTER TABLE public.tbl_user OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 25354)
-- Name: tbl_user_has_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_user_has_role (
                                          id integer NOT NULL,
                                          role_id integer,
                                          created_at timestamp(6) without time zone,
                                          updated_at timestamp(6) without time zone,
                                          user_id bigint,
                                          created_by character varying(255),
                                          updated_by character varying(255)
);


ALTER TABLE public.tbl_user_has_role OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 25353)
-- Name: tbl_user_has_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_user_has_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_user_has_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 25343)
-- Name: tbl_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4918 (class 0 OID 25298)
-- Dependencies: 218
-- Data for Name: tbl_address; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tbl_address (address_type, created_at, id, updated_at, user_id, apartment_number, building, city, country, floor, street, street_number, created_by, updated_by) VALUES (NULL, '2025-04-26 20:04:41.277', 1, '2025-04-26 20:04:41.277', 5, '1', 'building', 'Đà Nẵng', 'Việt Nam', '10', 'Phạm Như Xương', '1', NULL, NULL);
INSERT INTO public.tbl_address (address_type, created_at, id, updated_at, user_id, apartment_number, building, city, country, floor, street, street_number, created_by, updated_by) VALUES (NULL, '2025-04-26 22:21:47.337', 2, '2025-04-26 22:21:47.337', 7, '1', 'building', 'Đà Nẵng', 'Việt Nam', '10', 'Phạm Như Xương', '1', NULL, NULL);
INSERT INTO public.tbl_address (address_type, created_at, id, updated_at, user_id, apartment_number, building, city, country, floor, street, street_number, created_by, updated_by) VALUES (NULL, '2025-04-26 22:25:10.399', 3, '2025-04-26 22:25:10.399', 9, '1', 'building', 'Đà Nẵng', 'Việt Nam', '10', 'Phạm Như Xương', '1', NULL, NULL);


--
-- TOC entry 4920 (class 0 OID 25306)
-- Dependencies: 220
-- Data for Name: tbl_group; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4922 (class 0 OID 25316)
-- Dependencies: 222
-- Data for Name: tbl_group_has_user; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4924 (class 0 OID 25322)
-- Dependencies: 224
-- Data for Name: tbl_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4926 (class 0 OID 25330)
-- Dependencies: 226
-- Data for Name: tbl_role; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tbl_role (id, created_at, updated_at, description, name, created_by, updated_by) VALUES (1, NULL, NULL, NULL, 'sysadmin', NULL, NULL);
INSERT INTO public.tbl_role (id, created_at, updated_at, description, name, created_by, updated_by) VALUES (2, NULL, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO public.tbl_role (id, created_at, updated_at, description, name, created_by, updated_by) VALUES (3, NULL, NULL, NULL, 'manager', NULL, NULL);
INSERT INTO public.tbl_role (id, created_at, updated_at, description, name, created_by, updated_by) VALUES (4, NULL, NULL, NULL, 'user', NULL, NULL);


--
-- TOC entry 4928 (class 0 OID 25338)
-- Dependencies: 228
-- Data for Name: tbl_role_has_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4930 (class 0 OID 25344)
-- Dependencies: 230
-- Data for Name: tbl_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tbl_user (date_of_birth, created_at, id, updated_at, phone, email, first_name, last_name, password, username, created_by, updated_by, gender, status, type) VALUES ('2002-06-02', '2025-04-26 20:04:41.234', 5, '2025-04-26 20:04:41.234', '0328363633', 'user1@gmail.com', 'user', '1', NULL, 'user1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.tbl_user (date_of_birth, created_at, id, updated_at, phone, email, first_name, last_name, password, username, created_by, updated_by, gender, status, type) VALUES ('2002-02-06', NULL, 1, NULL, '0328363633', 'pvabao.020602@gmail.com', 'Bảo', 'Phạm Vương Anh', '$2a$10$Xrh0q5goXTpT80GIcBD.TusVGP5RZ4UXmzA0sMbQRDIuD/wKVg2O6', 'baopva', NULL, NULL, NULL, 'ACTIVE', NULL);
INSERT INTO public.tbl_user (date_of_birth, created_at, id, updated_at, phone, email, first_name, last_name, password, username, created_by, updated_by, gender, status, type) VALUES ('2002-02-06', NULL, 2, NULL, NULL, 'admin@gmail.com', 'Admin', NULL, '$2a$10$Xrh0q5goXTpT80GIcBD.TusVGP5RZ4UXmzA0sMbQRDIuD/wKVg2O6', 'admin', NULL, NULL, NULL, 'ACTIVE', NULL);
INSERT INTO public.tbl_user (date_of_birth, created_at, id, updated_at, phone, email, first_name, last_name, password, username, created_by, updated_by, gender, status, type) VALUES ('2002-02-06', NULL, 3, NULL, NULL, 'manager@gmail.com', 'Manager', NULL, '$2a$10$Xrh0q5goXTpT80GIcBD.TusVGP5RZ4UXmzA0sMbQRDIuD/wKVg2O6', 'manager', NULL, NULL, NULL, 'ACTIVE', NULL);
INSERT INTO public.tbl_user (date_of_birth, created_at, id, updated_at, phone, email, first_name, last_name, password, username, created_by, updated_by, gender, status, type) VALUES ('2002-02-06', NULL, 4, NULL, NULL, 'user@gmail.com', 'User', NULL, '$2a$10$Xrh0q5goXTpT80GIcBD.TusVGP5RZ4UXmzA0sMbQRDIuD/wKVg2O6', 'user', NULL, NULL, NULL, 'ACTIVE', NULL);
INSERT INTO public.tbl_user (date_of_birth, created_at, id, updated_at, phone, email, first_name, last_name, password, username, created_by, updated_by, gender, status, type) VALUES ('2002-06-02', '2025-04-26 22:21:47.337', 7, '2025-04-26 22:21:47.337', '0328363633', 'user2@gmail.com', 'user', '2', NULL, 'user2', NULL, NULL, 'FEMALE', 'NONE', 'USER');
INSERT INTO public.tbl_user (date_of_birth, created_at, id, updated_at, phone, email, first_name, last_name, password, username, created_by, updated_by, gender, status, type) VALUES ('2002-06-02', '2025-04-26 22:25:10.397', 9, '2025-04-27 16:28:41.292', '0328363633', 'user3@gmail.com', 'user', '4', NULL, 'user3', NULL, NULL, 'FEMALE', 'INACTIVE', 'USER');


--
-- TOC entry 4932 (class 0 OID 25354)
-- Dependencies: 232
-- Data for Name: tbl_user_has_role; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tbl_user_has_role (id, role_id, created_at, updated_at, user_id, created_by, updated_by) VALUES (1, 2, NULL, NULL, 2, NULL, NULL);
INSERT INTO public.tbl_user_has_role (id, role_id, created_at, updated_at, user_id, created_by, updated_by) VALUES (2, 3, NULL, NULL, 3, NULL, NULL);
INSERT INTO public.tbl_user_has_role (id, role_id, created_at, updated_at, user_id, created_by, updated_by) VALUES (3, 4, NULL, NULL, 4, NULL, NULL);


--
-- TOC entry 4938 (class 0 OID 0)
-- Dependencies: 217
-- Name: tbl_address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_address_id_seq', 3, true);


--
-- TOC entry 4939 (class 0 OID 0)
-- Dependencies: 221
-- Name: tbl_group_has_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_group_has_user_id_seq', 1, false);


--
-- TOC entry 4940 (class 0 OID 0)
-- Dependencies: 219
-- Name: tbl_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_group_id_seq', 1, false);


--
-- TOC entry 4941 (class 0 OID 0)
-- Dependencies: 223
-- Name: tbl_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_permission_id_seq', 1, false);


--
-- TOC entry 4942 (class 0 OID 0)
-- Dependencies: 227
-- Name: tbl_role_has_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_role_has_permission_id_seq', 1, false);


--
-- TOC entry 4943 (class 0 OID 0)
-- Dependencies: 225
-- Name: tbl_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_role_id_seq', 1, false);


--
-- TOC entry 4944 (class 0 OID 0)
-- Dependencies: 231
-- Name: tbl_user_has_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_user_has_role_id_seq', 1, false);


--
-- TOC entry 4945 (class 0 OID 0)
-- Dependencies: 229
-- Name: tbl_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_user_id_seq', 9, true);


--
-- TOC entry 4746 (class 2606 OID 25304)
-- Name: tbl_address tbl_address_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_address
    ADD CONSTRAINT tbl_address_pkey PRIMARY KEY (id);


--
-- TOC entry 4752 (class 2606 OID 25320)
-- Name: tbl_group_has_user tbl_group_has_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_group_has_user
    ADD CONSTRAINT tbl_group_has_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4748 (class 2606 OID 25312)
-- Name: tbl_group tbl_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_group
    ADD CONSTRAINT tbl_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4750 (class 2606 OID 25314)
-- Name: tbl_group tbl_group_role_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_group
    ADD CONSTRAINT tbl_group_role_id_key UNIQUE (role_id);


--
-- TOC entry 4754 (class 2606 OID 25328)
-- Name: tbl_permission tbl_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_permission
    ADD CONSTRAINT tbl_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4758 (class 2606 OID 25342)
-- Name: tbl_role_has_permission tbl_role_has_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_role_has_permission
    ADD CONSTRAINT tbl_role_has_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4756 (class 2606 OID 25336)
-- Name: tbl_role tbl_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_role
    ADD CONSTRAINT tbl_role_pkey PRIMARY KEY (id);


--
-- TOC entry 4764 (class 2606 OID 25358)
-- Name: tbl_user_has_role tbl_user_has_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_user_has_role
    ADD CONSTRAINT tbl_user_has_role_pkey PRIMARY KEY (id);


--
-- TOC entry 4760 (class 2606 OID 25350)
-- Name: tbl_user tbl_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_user
    ADD CONSTRAINT tbl_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4762 (class 2606 OID 25352)
-- Name: tbl_user tbl_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_user
    ADD CONSTRAINT tbl_user_username_key UNIQUE (username);


--
-- TOC entry 4768 (class 2606 OID 25379)
-- Name: tbl_role_has_permission fk7qnieb63nch1w822p22wu7il9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_role_has_permission
    ADD CONSTRAINT fk7qnieb63nch1w822p22wu7il9 FOREIGN KEY (role_id) REFERENCES public.tbl_role(id);


--
-- TOC entry 4765 (class 2606 OID 25359)
-- Name: tbl_group fke17sm3r6jxwtd4dsbummwt6y0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_group
    ADD CONSTRAINT fke17sm3r6jxwtd4dsbummwt6y0 FOREIGN KEY (role_id) REFERENCES public.tbl_role(id);


--
-- TOC entry 4769 (class 2606 OID 25374)
-- Name: tbl_role_has_permission fkimpu2q9vas7utdl3gti0w2ied; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_role_has_permission
    ADD CONSTRAINT fkimpu2q9vas7utdl3gti0w2ied FOREIGN KEY (permission_id) REFERENCES public.tbl_permission(id);


--
-- TOC entry 4766 (class 2606 OID 25364)
-- Name: tbl_group_has_user fkk23xt6t0rhoc1s185sekeayf9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_group_has_user
    ADD CONSTRAINT fkk23xt6t0rhoc1s185sekeayf9 FOREIGN KEY (group_id) REFERENCES public.tbl_group(id);


--
-- TOC entry 4770 (class 2606 OID 25389)
-- Name: tbl_user_has_role fklndw06guu8xedftiuosbtbr0a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_user_has_role
    ADD CONSTRAINT fklndw06guu8xedftiuosbtbr0a FOREIGN KEY (user_id) REFERENCES public.tbl_user(id);


--
-- TOC entry 4771 (class 2606 OID 25384)
-- Name: tbl_user_has_role fknbcb2rhv9gavk1vtounetntw0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_user_has_role
    ADD CONSTRAINT fknbcb2rhv9gavk1vtounetntw0 FOREIGN KEY (role_id) REFERENCES public.tbl_role(id);


--
-- TOC entry 4767 (class 2606 OID 25369)
-- Name: tbl_group_has_user fkqpbvdln7wyp9dnjvrx0mrrnk1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_group_has_user
    ADD CONSTRAINT fkqpbvdln7wyp9dnjvrx0mrrnk1 FOREIGN KEY (user_id) REFERENCES public.tbl_user(id);


-- Completed on 2025-05-04 22:15:17

--
-- PostgreSQL database dump complete
--

