spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/backend_service}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:150208}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
#      ddl-auto: create
#      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sendgrid:
    api-key: SG.Qa6E2CDHRdKLsAIJm22nKQ.On2HRLY6IxWCeNv0N6m0xFE2KFdIGCbCcW2rKCenqnM
    from-email: baobanbanhbao33@gmail.com

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0