spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/backend_service}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:150208}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
#      ddl-auto: create
#      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sendgrid:
    api-key: ${SENDGRID_API_KEY:SG.Qa6E2CDHRdKLsAIJm22nKQ.On2HRLY6IxWCeNv0N6m0xFE2KFdIGCbCcW2rKCenqnM}
    from-email: ${SENDGRID_FROM_EMAIL:baobanbanhbao33@gmail.com}
    template-id: ${SENDGRID_TEMPLATE_ID:d-7138fd180a074616849cf0cfaad31d7c}
    verification-link: ${SENDGRID_VERIFICATION_LINK:http://localhost:8080/user/confirm-email}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

# Generate HMAC Authentication Code: https://www.devglan.com/online-tools/hmac-sha256-online
jwt:
  expiryMinutes: 60
  expiryDay: 14
  accessKey: IIwLeRIVsznVTPFEYmA6HiVVBrlKkKqC36OpWzqw8mk=
  refreshKey: tvszknimPZQEdy3c9TCERBLAkOyoCc2ZvOmGcHsRJgg=