spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
#      ddl-auto: create
#      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: backend-service
    server: ${BACKEND_SERVICE:http://localhost:${server.port}}
    title: Backend service
    version: 1.0.0